name: Action

on: [ push, pull_request ]

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install flake8
      - name: Run linting
        run:
            flake8 src/lstm.py
            flake8 src/gru.py
            flake8 src/arima.py
            flake8 src/functions.py
      - name: Run Python
        run:
            python src/lstm.py
            python src/gru.py
            python src/arima.py
            python src/functions.py
